name: Docker Base Tags CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  base-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [base, xtensa-base, riscv-base]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - ${{ matrix.base }} tag
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.base }}.Dockerfile
          build-args: |
            NIGHTLY_TOOLCHAIN_VERSION=nightly
            XTENSA_TOOLCHAIN_VERSION=1.60.0.1
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:${{ matrix.base }}
  trigger-espidf-tags:
    needs: base-tags
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflows
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: build-espidf-tags
