name: Docker Base Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push - Base image
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: base.Dockerfile
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: sergiogasquez/esp-rs-env:base, sergiogasquez/esp-rs-env:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Build and push - Xtensa base image
        uses: docker/build-push-action@v2
        with:
          file: xtensa-base.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:xtensa-base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Build and push - RiscV base image
        uses: docker/build-push-action@v2
        with:
          file: riscv-base.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:riscv-base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run:
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: build-espidf-images