name: Docker Esp Idf Versions Images CI

on:
  repository_dispatch:
    types: [build-espidf-images]

jobs:
  esp-idf-versions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - espidf_v4.4
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ESP_IDF_VERSION=v4.4
            ESP_IDF_BRANCH=release/v4.4
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:espidf_v4.4
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Build and push - espidf_v5.0
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ESP_IDF_VERSION=v5.0
            ESP_IDF_BRANCH=master
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:espidf_v5.0, sergiogasquez/esp-rs-env:master
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        name: Build and push - espidf_v4.3.2
        uses: docker/build-push-action@v2
        with:
          build-args: |
            ESP_IDF_VERSION=v4.3.2
            ESP_IDF_BRANCH=release/v4.3
          context: .
          platforms: linux/amd64
          push: true
          tags: sergiogasquez/esp-rs-env:espidf_v4.3.2
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run:
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
