name: Docker Esp Idf Versions Images CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  esp32c3-training:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - esp32c3-training
        uses: docker/build-push-action@v2
        with:
          file: esp32c3-training.Dockerfile
          build-args: |
            NIGHTLY_VERSION=nightly-2022-03-10
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: sergiogasquez/esp-rs-env:esp32c3-training