name: Publish IDF-Rust Tags

on:
  workflow_dispatch:
    inputs:
      rust-build-branch:
        description: 'Branch of rust-build to use'
        required: true
        default: 'main'
      toolchain-version:
        description: 'Version of Rust toolchain'
        required: true
        default: '1.61.0.0'

jobs:
  # release-v4_4:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       board: ['esp32', 'esp32s2', 'esp32s3', 'esp32c3']
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: ${{ github.event.inputs.rust-build-branch }}
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Set Swap Space
  #       uses: pierotofy/set-swap-space@master
  #       with:
  #         swap-size-gb: 10
  #     -
  #       name: Build - ${{ matrix.board }}_v4.4_${{ github.event.inputs.toolchain-version }} tag
  #       uses: docker/build-push-action@v2
  #       with:
  #         file: idf-rust.Containerfile
  #         build-args: |
  #           XTENSA_TOOLCHAIN_VERSION=${{ github.event.inputs.toolchain-version }}
  #           ESP_IDF_VERSION=release/v4.4
  #           ESP_BOARD=${{ matrix.board }}
  #         context: .
  #         platforms: linux/amd64, linux/arm64
  #         push: false
  master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ['esp32', 'esp32s2', 'esp32s3', 'esp32c3']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.rust-build-branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      # -
      #   name: Build - ${{ matrix.board }}_master_${{ github.event.inputs.toolchain-version }} tag
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: idf-rust.Containerfile
      #     build-args: |
      #       XTENSA_TOOLCHAIN_VERSION=${{ github.event.inputs.toolchain-version }}
      #       ESP_IDF_VERSION=master
      #       ESP_BOARD=${{ matrix.board }}
      #     context: .
      #     platforms: linux/amd64
      #     push: false
      - name: Build image
        run: docker build --build-arg XTENSA_TOOLCHAIN_VERSION=${{ github.event.inputs.toolchain-version }} --build-arg ESP_IDF_VERSION=master --build-arg ESP_BOARD=${{ matrix.board }} -t idf-rust -f idf-rust.Containerfile .
      - name: Test image
        run: |
          docker run -it --rm -u esp --name idf-rust idf-rust
          docker exec -it -u esp idf-rust bash -c 'git clone https://github.com/ivmarkov/rust-esp32-std-demo.git &&  source export-esp.sh && cd rust-esp32-std-demo && export RUST_ESP32_STD_DEMO_WIFI_SSID=ssid && export RUST_ESP32_STD_DEMO_WIFI_PASS=pass && cargo +esp build --target xtensa-esp32-espidf --release'
      -
        name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/esp-rs-env:${{ matrix.board }}_master_${{ github.event.inputs.toolchain-version }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
